<?xml version="1.0" encoding="UTF-8"?>
<integrity name="Integrity JUnit Testing" timestamp="12.01.16 09:44" isotimestamp="2016-01-12T09:44:39" duration="3.578">
  <variables />
  <suite id="0" name="integrity.basic.exceptions.runtimeExceptions.runtimeExceptionInTableTest" timestamp="12.01.16 09:44:39.0893">
    <setup />
    <variables />
    <statements>
      <tabletest id="1" line="8" name="throwRuntimeExceptionTest" description="Throws a runtime exception" fixture="de.gebit.integrity.tests.fixtures.basic.NoOpFixture#throwRuntimeException" timestamp="12.01.16 09:44:39.0894">
        <parameters />
        <results duration="2.216" successCount="0" failureCount="0" exceptionCount="1">
          <result duration="0.371" description="Throws a runtime exception" type="exception" exceptionMessage="This is a runtime exception in a tabletest" exceptionTrace="java.lang.RuntimeException: This is a runtime exception in a tabletest&#xD;&#xA;&#x9;at de.gebit.integrity.tests.fixtures.basic.NoOpFixture.throwRuntimeException(NoOpFixture.java:197)&#xD;&#xA;&#x9;at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)&#xD;&#xA;&#x9;at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)&#xD;&#xA;&#x9;at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)&#xD;&#xA;&#x9;at java.lang.reflect.Method.invoke(Method.java:606)&#xD;&#xA;&#x9;at de.gebit.integrity.fixtures.FixtureWrapper.execute(FixtureWrapper.java:313)&#xD;&#xA;&#x9;at de.gebit.integrity.runner.DefaultTestRunner.executeTableTest(DefaultTestRunner.java:1411)&#xD;&#xA;&#x9;at de.gebit.integrity.runner.DefaultTestRunner.executeSuite(DefaultTestRunner.java:989)&#xD;&#xA;&#x9;at de.gebit.integrity.runner.DefaultTestRunner.callSuiteSingle(DefaultTestRunner.java:788)&#xD;&#xA;&#x9;at de.gebit.integrity.runner.DefaultTestRunner.runInternal(DefaultTestRunner.java:623)&#xD;&#xA;&#x9;at de.gebit.integrity.runner.DefaultTestRunner.run(DefaultTestRunner.java:501)&#xD;&#xA;&#x9;at de.gebit.integrity.runner.DefaultTestRunner.run(DefaultTestRunner.java:436)&#xD;&#xA;&#x9;at de.gebit.integrity.tests.junit.IntegrityJUnitTest.executeIntegritySuite(IntegrityJUnitTest.java:99)&#xD;&#xA;&#x9;at de.gebit.integrity.tests.junit.basic.exceptions.RuntimeExceptions.runtimeExceptionInTableTest(RuntimeExceptions.java:52)&#xD;&#xA;&#x9;at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)&#xD;&#xA;&#x9;at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)&#xD;&#xA;&#x9;at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)&#xD;&#xA;&#x9;at java.lang.reflect.Method.invoke(Method.java:606)&#xD;&#xA;&#x9;at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)&#xD;&#xA;&#x9;at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)&#xD;&#xA;&#x9;at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)&#xD;&#xA;&#x9;at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)&#xD;&#xA;&#x9;at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)&#xD;&#xA;&#x9;at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)&#xD;&#xA;&#x9;at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)&#xD;&#xA;&#x9;at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)&#xD;&#xA;&#x9;at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)&#xD;&#xA;&#x9;at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)&#xD;&#xA;&#x9;at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)&#xD;&#xA;&#x9;at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)&#xD;&#xA;&#x9;at org.junit.runners.ParentRunner.run(ParentRunner.java:363)&#xD;&#xA;&#x9;at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)&#xD;&#xA;&#x9;at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)&#xD;&#xA;&#x9;at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)&#xD;&#xA;&#x9;at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:675)&#xD;&#xA;&#x9;at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)&#xD;&#xA;&#x9;at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)&#xD;&#xA;">
            <parameters>
              <parameter name="message" value="This is a runtime exception in a tabletest" />
            </parameters>
          </result>
        </results>
      </tabletest>
    </statements>
    <teardown />
    <result duration="3.094" successCount="0" failureCount="0" exceptionCount="1" testExceptionCount="1" callExceptionCount="0" />
  </suite>
</integrity>

