<?xml version="1.0" encoding="UTF-8"?>
<integrity name="Integrity JUnit Testing" timestamp="06.03.15 08:52" isotimestamp="2015-03-06T08:52:59" duration="21.631">
  <variables />
  <suite id="0" name="integrity.basic.exceptions.runtimeExceptions.runtimeExceptionInTest" timestamp="06.03.15 08:52:59.0375">
    <setup />
    <variables />
    <statements>
      <test id="1" line="4" name="throwRuntimeExceptionTest" description="Throws a runtime exception" fixture="de.gebit.integrity.tests.fixtures.basic.NoOpFixture#throwRuntimeException" timestamp="06.03.15 08:52:59.0375">
        <results duration="3.593" successCount="0" failureCount="0" exceptionCount="1">
          <result duration="3.593" description="Throws a runtime exception" type="exception" exceptionMessage="This is a runtime exception in a test" exceptionTrace="java.lang.RuntimeException: This is a runtime exception in a test&#xD;&#xA;&#x9;at de.gebit.integrity.tests.fixtures.basic.NoOpFixture.throwRuntimeException(NoOpFixture.java:176)&#xD;&#xA;&#x9;at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)&#xD;&#xA;&#x9;at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)&#xD;&#xA;&#x9;at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)&#xD;&#xA;&#x9;at java.lang.reflect.Method.invoke(Method.java:597)&#xD;&#xA;&#x9;at de.gebit.integrity.fixtures.FixtureWrapper.execute(FixtureWrapper.java:283)&#xD;&#xA;&#x9;at de.gebit.integrity.runner.DefaultTestRunner.executeTest(DefaultTestRunner.java:1222)&#xD;&#xA;&#x9;at de.gebit.integrity.runner.DefaultTestRunner.executeSuite(DefaultTestRunner.java:953)&#xD;&#xA;&#x9;at de.gebit.integrity.runner.DefaultTestRunner.callSuiteSingle(DefaultTestRunner.java:757)&#xD;&#xA;&#x9;at de.gebit.integrity.runner.DefaultTestRunner.runInternal(DefaultTestRunner.java:608)&#xD;&#xA;&#x9;at de.gebit.integrity.runner.DefaultTestRunner.run(DefaultTestRunner.java:498)&#xD;&#xA;&#x9;at de.gebit.integrity.runner.DefaultTestRunner.run(DefaultTestRunner.java:433)&#xD;&#xA;&#x9;at de.gebit.integrity.tests.junit.IntegrityJUnitTest.executeIntegritySuite(IntegrityJUnitTest.java:99)&#xD;&#xA;&#x9;at de.gebit.integrity.tests.junit.basic.exceptions.RuntimeExceptions.runtimeExceptionInTest(RuntimeExceptions.java:37)&#xD;&#xA;&#x9;at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)&#xD;&#xA;&#x9;at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)&#xD;&#xA;&#x9;at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)&#xD;&#xA;&#x9;at java.lang.reflect.Method.invoke(Method.java:597)&#xD;&#xA;&#x9;at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)&#xD;&#xA;&#x9;at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)&#xD;&#xA;&#x9;at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)&#xD;&#xA;&#x9;at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)&#xD;&#xA;&#x9;at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)&#xD;&#xA;&#x9;at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)&#xD;&#xA;&#x9;at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)&#xD;&#xA;&#x9;at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)&#xD;&#xA;&#x9;at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)&#xD;&#xA;&#x9;at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)&#xD;&#xA;&#x9;at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)&#xD;&#xA;&#x9;at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)&#xD;&#xA;&#x9;at org.junit.runners.ParentRunner.run(ParentRunner.java:309)&#xD;&#xA;&#x9;at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)&#xD;&#xA;&#x9;at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)&#xD;&#xA;&#x9;at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)&#xD;&#xA;&#x9;at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:675)&#xD;&#xA;&#x9;at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)&#xD;&#xA;&#x9;at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)&#xD;&#xA;">
            <parameters>
              <parameter name="message" value="This is a runtime exception in a test" />
            </parameters>
          </result>
        </results>
      </test>
    </statements>
    <teardown />
    <result duration="15.220" successCount="0" failureCount="0" exceptionCount="1" testExceptionCount="1" callExceptionCount="0" />
  </suite>
</integrity>

